export const title = "Polityka prywatności";

const section1Title = "I. Postanowienia ogólne";
const section1Content = `
<ol style="padding-left: 15px;">
    <li>Polityka prywatności określa zasady przetwarzania i ochrony danych osobowych Użytkowników i Klientów (w tym potencjalnych klientów) korzystających ze sklepu internetowego dostępnego pod adresem internetowym: www.odkrywajcie.pl, zwanego dalej Sklepem.</li>
    <li>Polityka prywatności Sklepu ma charakter informacyjny.</li>
    <li>Administratorem danych osobowych Użytkowników Sklepu, w rozumieniu rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych) z dnia 27 kwietnia 2016 r. (Dz. Urz. UE. L Nr 119, str. 1), zwanym dalej RODO jest Elżbieta Dzierzęga, prowadząca nierejestrowaną działalność gospodarczą, zamieszkała przy ul. Miłosza 26, 41-700 Ruda Śląska, adres poczty elektronicznej: kontakt@odkrywajcie.pl, nr telefonu kontaktowego: +48 721 956 975, zwany dalej Administratorem i będący jednocześnie Usługodawcą Sklepu Internetowego i Sprzedawcą.</li>
    <li>Dane osobowe Użytkownika są przetwarzane zgodnie z przepisami dotyczącymi ochrony danych osobowych oraz ustawą z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (Dz. U. Nr 144, poz. 1204, z późn. zm.).</li>
    <li>Administrator dokłada wszelkiej staranności w celu ochrony interesów osób, których zbierane dane dotyczą, a w szczególności zapewnia, że dane te są przetwarzane zgodnie z prawem. Dane osobowe są zbierane przez Administratora dla zdefiniowanych, zgodnych z prawem celów i niepoddawane dalszemu przetwarzaniu niezgodnemu z tymi celami. Administrator oświadcza, że zbierane przez niego dane są przechowywane w postaci umożliwiającej identyfikację osób, których dotyczą, nie dłużej niż jest to niezbędne do osiągnięcia danego celu przetwarzania.</li>
    <li>Celem Polityki Prywatności jest określenie działań podejmowanych przez Administratora, w zakresie danych osobowych gromadzonych za pośrednictwem Sklepu internetowego oraz powiązanego ze Sklepem internetowym narzędzia wykorzystywanego przez Klientów do składania Zamówienia.</li>
    <li>Klient, który korzysta z narzędza udostępnionego w ramach Sklepu internetowego, potwierdza zapoznanie się z postanowieniami Polityki Prywatności i Regulaminu Sklepu internetowego, a także wyraża zgodę, jeżeli zachodzi taka potrzeba, na wykorzystywanie jego danych osobowych zgodnie z Regulaminem Sklepu internetowego oraz Polityką Prywatności (w tym celu zaznacza odpowiednie pola wyboru, kierując się komunikatami pojawiającymi się na stronie internetowej Sklepu internetowego).</li>
    <li>Wszystkie zbierane przez Administratora dane chronione są z użyciem racjonalnych środków technicznych i organizacyjnych oraz procedur bezpieczeństwa, w celu zabezpieczenia ich przed dostępem osób nieupoważnionych lub ich nieupoważnionym wykorzystaniem.</li>
    <li>Administrator Sklepu internetowego na zasadach określonych w Regulaminie oraz w Polityce Prywatności posiada wyłączny dostęp do danych. Dostęp do danych osobowych Klienta może być również powierzony innym podmiotom, np. za pomocą, których Klient dokonuje płatności, które to podmioty gromadzą, przetwarzają i przechowują dane osobowe zgodnie ze swoimi regulaminami i politykami prywatności. Dostęp do danych osobowych Klienta jest udzielany przedmiotowym podmiotom w zakresie niezbędnym i tylko takim, który zapewni odpowiednią realizację usług. Podmioty zewnętrzne przetwarzają powierzone dane tylko na podstawie stosownych umów powierzenia.</li>
    <li>Wszelkie słowa i wyrażenia występujące w Polityce Prywatności rozpoczynające się wielką literą (np. Sprzedawca, Sklep internetowy, Klient, Zamówienie) należy rozumieć zgodnie z definicjami zawartymi w Regulaminie Sklepu internetowego dostępnym na stronie internetowej Sklepu Internetowego.</li>
</ol>
`;

const section2Title = "II. Gromadzenie, pozyskiwanie, zakres i cel zbierania danych osobowych";
const section2Content = `
<ol style="padding-left: 15px;">
    <li>Administrator pozyskuje informacje o użytkownikach m.in. poprzez gromadzenie logów serwera za pośrednictwem operatora hostingowego.</li>
    <li>Dane zapisane w logach serwera nie są kojarzone z konkretnymi osobami korzystającymi ze strony internetowej Sklepu i nie są wykorzystywane w celu identyfikacji osób korzystających ze Sklepu.</li>
    <li>Logi serwera stanowią wyłącznie materiał pomocniczy służący do administrowania Serwisem, a ich zawartość nie jest ujawniana nikomu poza osobami upoważnionymi do administrowania serwerem.</li>
    <li>Administrator informuje, że w związku z koniecznością wypełnienia formularza z danymi adresowymi w Sklepie internetowym, Klienci składający zamówienie w Sklepie internetowym mogą zostać zobowiązani do podania określonych danych, takich jak adres e-mail i adres dostawy. Podanie wyszczególnionych podczas procesu zamówienia  danych jest konieczne do złożenia zamówienia.</li>
    <li>Administrator w ramach Sklepu internetowego może gromadzić dane osobowe Klientów i potencjalnych Klientów kontaktujących się z Administratorem w ramach obsługi klienta, a które to dane osobowe są niezbędne do zrealizowania danej prośby Klienta i kontaktu z nim w celu udzielenia odpowiedzi. Podstawą przetwarzania danych jest art. 6 ust. 1 lit. a RODO - zgoda na przetwarzanie. Podstawą prawną przetwarzania po ewentualnym zakończeniu kontaktu będzie usprawiedliwiony cel w postaci archiwizacji korespondencji na potrzeby wykazania jej przebiegu w przyszłości (stosownie do art. 6 ust. 1 lit. f RODO). Jeżeli po kontakcie dojdzie do zawarcia umowy, dane będą przetwarzane na podstawie art. 6 ust. 1 lit. b RODO.</li>
    <li>Administrator przetwarza dane osobowe Klientów niezbędne do prawidłowej realizacji usług dostępnych w Sklepie internetowym i jest uprawniony do wykorzystywania zgromadzonych i przechowywanych w ramach Sklepu internetowego danych w następujących celach: <ol type='a'><li>złożenia zamówienia w Sklepie internetowym (na podstawie art. 6 ust. 1 lit. b RODO),</li><li>zawarcia i realizacji Umowy sprzedaży lub Umowy o świadczenie Usługi elektronicznej (na podstawie art. 6 ust. 1 lit. b RODO),</li><li>marketingu bezpośredniego własnych produktów lub usług (na podstawie art. 6 ust. 1 lit. f RODO),</li><li>zapewnienia pełnej obsługi Użytkownika (na podstawie art. 6 ust. 1 lit. b i f RODO),</li><li>dostosowywania oferty i doświadczeń Użytkownika, w tym reklam, we właściwościach Sklepu (na podstawie art. 6 ust. 1 lit. b i f RODO),</li><li>kontaktowania się z Użytkownikami, w szczególności w celach związanych ze świadczeniem usług, obsługą Użytkowników, dozwolonymi działaniami marketingowymi i reklamowymi (na podstawie art. 6 ust. 1 lit. a, b i f RODO),</li><li>przeprowadzania badań i analiz w celu poprawy działania dostępnych usług (na podstawie art. 6 ust. 1 lit. b i f RODO),</li><li>egzekwowania przestrzegania Regulaminu Sklepu internetowego (na podstawie art. 6 ust. 1 lit. b i f RODO),</li><li>wysyłki Newslettera (na podstawie art. 6 ust. 1 lit. a RODO),</li><li>przekazania danych osobowych Klientów do ING Banku Śląskiego S.A. w związku ze: <ol type='i'><li>świadczeniem przez Bank na rzecz Sklepu internetowego usługi udostępnienia infrastruktury do obsługi płatności przez Internet (na podstawie art. 6 ust. 1 lit. f RODO),</li><li>obsługą i rozliczaniem przez Bank płatności dokonywanych przez klientów Sklepu internetowego przez Internet przy użyciu instrumentów płatniczych (na podstawie art. 6 ust. 1 lit. f RODO),</li><li>w celu weryfikacji przez Bank należytego wykonania umów zawartych ze Sklepem internetowym, w szczególności zapewnienia ochrony interesów płatników w związku ze składanymi przez nich reklamacjami (na podstawie art. 6 ust. 1 lit. f RODO).</li></ol></li></ol></li>
    <li>Administrator jest uprawniony do przechowywania zgromadzonych i śledzonych w Sklepie internetowym danych wyłącznie w zakresie realizacji powyżej określonych celów.</li>
    <li>Administrator jest uprawniony do automatycznego pozyskiwania i rejestrowania danych przekazywanych na serwer przez przeglądarki internetowe lub urządzenia Klientów, np. adres IP, parametry oprogramowania i sprzętu, przeglądane strony, numer identyfikacyjny urządzenia mobilnego oraz inne dane dotyczące urządzeń i korzystania z systemów. Gromadzenie powyższych informacji następować będzie w przypadku korzystania ze Sklepu internetowego.</li>
    <li>Administrator zbiera, przetwarza i przechowuje następujące dane Klientów:<ol type='a'><li>adres poczty elektronicznej (adres e-mail),</li><li>imię i nazwisko</li><li>adres dostawy Towaru (ulica, numer domu, numer lokalu, kod pocztowy, miejscowość, kraj),</li><li>adres zamieszkania/prowadzenia działalności/siedziby (jeżeli jest inny niż adres dostawy),</li><li>numer telefonu.</li></ol></li>
    <li>Sprzedawca oświadcza, iż podanie danych przez Klienta, w wyżej wskazanym zakresie, jest dobrowolne. Ich podanie może być jednak niezbędne do zawarcia i realizacji Umowy Sprzedaży lub Umowy o świadczenie Usługi Elektronicznej w Sklepie internetowym. Zakres wymaganych do zawarcia umowy danych wskazany jest uprzednio na stronie Sklepu internetowego oraz w Regulaminie Sklepu internetowego.</li>
    <li>W przypadku przekazania danych osobowych Klienta do Banku w związku z obsługą i rozliczaniem płatności dokonywanych przez Klienta płatności na rzecz Sklepu internetowego przez Internet przy użyciu instrumentów płatniczych, podanie danych jest wymagane w celu realizacji płatności i przekazania potwierdzenia jej dokonania przez Bank na rzecz Sklepu internetowego.</li>
    <li>W przypadku przekazania danych osobowych Klienta do Banku w celu weryfikacji przez Bank należytego wykonania umów zawartych ze Sklepem internetowym, w szczególności zapewnienia ochrony interesów płatników w związku ze składanymi przez nich reklamacjami podanie tych danych jest wymagane w celu umożliwienia realizacji umowy zawartej pomiędzy Sklepem internetowym a Bankiem.</li>
    <li>Przykładowi odbiorcy danych osobowych Klientów Sklepu internetowego: <ol type='a'><li>w przypadku Klienta, który korzysta w Sklepie internetowym ze sposobu dostawy przesyłką kurierską, Administrator powierza zebrane dane osobowe Klienta wybranemu przewoźnikowi lub pośrednikowi realizującemu przesyłki na zlecenie Administratora (w tym producentom Towarów),</li><li>w przypadku Klienta, który korzysta w Sklepie Internetowym ze sposobu płatności elektronicznych lub kartą płatniczą Administrator powierza zebrane dane osobowe Klienta, wybranemu podmiotowi obsługującemu płatności elektroniczne w Sklepie Internetowym, jak na przykład ING Bank Śląski S.A.</li></ol></li>
    <li>Administrator może udostępniać dane zanonimizowane innym podmiotom, w tym partnerom Sklepu internetowego w celu dokonania rozpoznania atrakcyjności reklam i usług dla Klientów, poprawy jakości i efektywności usług świadczonych przez Sklep internetowy lub wymienione podmioty lub udziału w badaniach naukowych.</li>
    <li>Administrator informuje, że stosuje następujące technologie śledzące działania podejmowane przez użytkownika/Klienta w ramach strony internetowej Sklepu:<ol type='a'><li>kod śledzenia Google Analitycs – w celu analizy statystyk strony internetowej Sklepu; informacje związane z Google Analytics znajdują się na stronie: https://support.google.com/analytics/answer/6004245,</li><li>piksel konwersji Facebooka (fragment kodu JavaScript) – w celu monitorowania zdarzeń na stronie internetowej Sklepu oraz zarządzania reklamami na Facebooku; informacje zbierane w ramach piksela Facebooka są anonimowe - nie pozwalają Administratorowi na identyfikację danej osoby. Więcej informacji związanych z wykorzystaniem przez Facebooka danych zbieranych poprzez piksel znajduje się tutaj: https://www.facebook.com/privacy/explanation.</li></ol></li>
</ol>
`;

const section3Title = "III. Zarządzanie plikami cookies";
const section3Content = `
<ol style="padding-left: 15px;">
    <li>Administrator zbiera w sposób automatyczny informacje zawarte w plikach cookies w celu gromadzenia danych związanych z korzystaniem ze Sklepu internetowego przez Klienta. Pliki cookies to mały fragment tekstu, który serwis internetowy wysyła do przeglądarki Użytkownika i który przeglądarka wysyła z powrotem przy następnych wejściach na witrynę. Używane są głównie do utrzymywania sesji np. poprzez wygenerowanie i odesłanie tymczasowego identyfikatora po logowaniu.</li>
    <li>Administrator wykorzystuje pliki cookies „sesyjne” przechowywane na urządzeniu końcowym Klienta do czasu jego wylogowania, wyłączenia strony internetowej lub wyłączenia przeglądarki internetowej oraz pliki cookies „stałe” przechowywane na urządzeniu końcowym Klienta przez czas określony w parametrach plików cookies lub do czasu ich usunięcia przez Klienta.</li>
    <li>Administrator w ramach Sklepu internetowego stosuje następujące rodzaje plików cookies: <ol type='a'><li>„niezbędne” pliki cookies, umożliwiające korzystanie z usług dostępnych w ramach Sklepu internetowego,</li><li>pliki cookies służące do zapewnienia bezpieczeństwa,</li><li>„wydajnościowe” pliki cookies, wykorzystywane do pozyskiwania informacji o sposobie korzystania ze strony internetowej Sklepu internetowego przez Użytkowników,</li><li>„reklamowe” pliki cookies, umożliwiające dostarczanie Użytkownikom treści reklamowych bardziej dostosowanych do ich zainteresowań,</li><li>„funkcjonalne” pliki cookies, umożliwiające „zapamiętanie” wybranych przez Użytkownika ustawień i dostosowanie Sklepu internetowego do Użytkownika.</li></ol></li>
    <li>Administrator usługi wykorzystuje cookies zewnętrzne w następujących celach: <ol type='a'><li>zbierania ogólnych i anonimowych danych statycznych za pośrednictwem narzędzi analitycznych: Google Analytics (administratorem cookies jest Google LLC z siedzibą w Stanach Zjednoczonych),</li><li>popularyzacji Sklepu internetowego za pomocą serwisu społecznościowego www.facebook.com (administrator cookies zewnętrznego: Facebook Inc z siedzibą w USA lub Facebook Ireland z siedzibą w Irlandii).</li></ol></li>
    <li>Google LLC oraz Facebook Inc są podmiotami z państwa trzeciego - Stanów Zjednoczonych oraz przystąpiły do PrivacyShield w celu zapewnienia odpowiedniego poziomu ochrony danych osobowych wymaganego przez RODO. Komisja Europejska potwierdziła odpowiedni poziom ochrony danych w przypadku przedsiębiorstw, które przystąpiły do PrivacyShield.</li>
    <li>Administrator zapewnia możliwość korzystania z funkcji społecznościowych, takich jak udostępnianie treści w serwisach społecznościowych oraz subskrypcja profilu społecznościowego. Korzystanie z tych funkcji może wiązać się z wykorzystywaniem plików cookies administratorów serwisów społecznościowego Facebook.</li>
    <li>Pliki cookies dostosowują i optymalizują Sklep internetowy i jego ofertę dla potrzeb Klientów poprzez takie działania jak tworzenie statystyk odsłon Sklepu internetowego oraz zapewnienie bezpieczeństwa jego użytkownikom.</li>
    <li>Pliki cookies niezbędne są również do utrzymania sesji Klienta po opuszczeniu przez niego Sklepu internetowego.</li>
    <li>Klient w każdej chwili za pomocą swojej przeglądarki internetowej może zmienić ustawienia dotyczące plików cookies, w tym może zablokować możliwość gromadzenia plików cookies.</li>
    <li>Zablokowanie możliwości gromadzenia plików cookies czy wprowadzenie innych zmian w ustawieniach dotyczących plików cookies na urządzeniu Klienta może utrudnić lub uniemożliwić korzystanie z usług i narzędzi Sklepu internetowego, w tym z możliwości złożenia Zamówienia.</li>
    <li>Klient, który nie chce wykorzystywania plików cookies w opisanych powyżej celach w każdej chwili może usunąć je ręcznie. Do zapoznania się ze szczegółową instrukcją postępowania należy odwiedzić stronę internetową producenta przeglądarki internetowej, z której aktualnie korzysta Klient. Więcej informacji na temat cookies dostępnych jest w menu pomocy każdej przeglądarki internetowej. Przykładowe przeglądarki internetowe obsługujące wspomniane pliki cookies to Internet Explorer, Mozilla Firefox, Google Chrome, Opera.</li>
    <li>Administrator może umożliwiać podmiotom zewnętrznym, np. dostawcom reklam czy dostawcom rozwiązań analitycznych, gromadzenie informacji z wykorzystaniem powyższych technologii bezpośrednio na stronie internetowej Sklepu internetowego. Zgromadzone w ten sposób dane podlegają postanowieniom polityk prywatności opracowanym przez te podmioty.</li>
    <li>Niektóre podmioty zewnętrzne działające w ramach Sklepu internetowego umożliwiają użytkownikom wycofanie zgody na gromadzenie i wykorzystywanie przez nie danych na potrzeby reklam bazujących na aktywności Klienta. Więcej informacji na ten temat i możliwość dokonania wyboru znajduje się na przykład na stronie internetowej: www.youronlinechoices.com.</li>
</ol>
`;

const section4Title = "IV. Prawa i obowiązki Administratora i Użytkowników";
const section4Content = `
<ol style="padding-left: 15px;">
    <li>Administrator ma prawo, a także ustawowy obowiązek do przekazania wybranych bądź wszystkich informacji dotyczących Użytkowników Strony organom władzy publicznej bądź podmiotom trzecim, które zgłoszą takie żądanie udzielenia informacji na podstawie obowiązujących przepisów prawa polskiego.</li>
    <li>Administrator nie powierza przetwarzania danych i nie udostępnia zebranych danych osobowych podmiotom niepowiązanym bez zgody zainteresowanych, chyba, że zachodzą następujące okoliczności: <ol type='a'><li>Administrator może korzystać ze wsparcia podmiotów zewnętrznych w celu świadczenia udostępnianych przez siebie usług, jednak podmioty te nie są upoważnione do niezależnego wykorzystywania danych osobowych przetwarzanych w imieniu Administratora, a wszelkie ich działania podlegają przepisom Polityki Prywatności Strony,</li><li>Administrator zachowuje prawo do udostępniania danych organom publicznym w prowadzeniu postępowań o możliwe naruszenia prawa lub w zwalczaniu ewentualnych naruszeń.</li></ol></li>
    <li>Klient/Użytkownik ma w każdym czasie prawo dostępu do swoich danych osobowych, a gromadzonych przez Administratora. Prawo to obejmuje możliwość weryfikacji, modyfikacji, uzupełnienia, usunięcia, ograniczenia przetwarzania danych, wniesienia sprzeciwu co do przetwarzania, przeniesienia danych, zaprzestania przetwarzania danych osobowych Użytkownika, a także prawo cofnięcia zgody na przetwarzanie danych w określonym celu, jeżeli Użytkownik taką zgodę uprzednio wyraził oraz prawo wniesienia skargi do organu nadzorczego. Przedmiotowe uprawnienia przysługują bez podania przyczyny.</li>
    <li>Klient/Użytkownik poprzez zaakceptowanie zaproponowanych przez Administratora oświadczeń zawartych w interaktywnych formularzach dostępnych na stronie internetowej, wyraża zgodę na przetwarzanie danych osobowych dla celów realizacji usług.</li>
    <li>W celu realizacji swoich praw Klient/Użytkownik może w każdym czasie przesłać stosowne oświadczenie woli na adres siedziby Administratora lub za pośrednictwem poczty elektronicznej.</li>
    <li>Usunięcie danych osobowych lub zaprzestanie ich przetwarzania przez Administratora może skutkować brakiem możliwości realizacji usług świadczonych za pośrednictwem Sklepu internetowego lub ograniczeniem możliwości korzystania z funkcjonalności Sklepu.</li>
    <li>Dane osobowe gromadzone w ramach celów określonych w Polityce Prywatności będą przechowywane przez okres realizacji usług (w tym usług elektronicznych) świadczonych przez Administratora oraz przez okres wynikający z terminów przedawnienia roszczeń, praw konsumenta, przepisów prawa podatkowego czy innych praw w tym zakresie (np. do czasu wycofania zgody na wysyłkę newslettera czy informacji handlowych).</li>
</ol>
`;

const section5Title = "V. Zmiany Polityki Prywatności";
const section5Content = `
<ol style="padding-left: 15px;">
    <li>Oferta Sklepu internetowego będzie w przyszłości ulegać rozszerzeniu. Oznacza to, że Administrator będzie zobowiązany lub uprawniony do wprowadzenia zmian w Polityce Prywatności.</li>
    <li>Nowe wersje Polityki Prywatności będą się pojawiały na stronie internetowej Sklepu internetowego wraz ze stosownym komunikatem.</li>
    <li>Każda zmiana Polityki Prywatności będzie obowiązywała od dnia powiadomienia o jej zmianie poprzez jej umieszczenie na stronie internetowej Sklepu internetowego. Wszelkie zmiany będą odpowiednio wyróżnione przez okres jednego miesiąca od dnia wprowadzenia zmian w Polityce Prywatności. W razie dodatkowych pytań dotyczących Polityki Prywatności Sklepu internetowego, prosimy o kontakt na podany przez Administratora adres poczty elektronicznej.</li>
</ol>
`;

export const content = `<div>
    <p style="margin-bottom: 0in; line-height: 100%; font-weight:bold">§ ${section1Title}</p>
    <div style="padding-left: 0px;">
        ${section1Content}
    </div>
    <p style="margin-bottom: 0in; line-height: 100%; font-weight:bold">§ ${section2Title}</p>
    <div style="padding-left: 0px;">
        ${section2Content}
    </div>
    <p style="margin-bottom: 0in; line-height: 100%; font-weight:bold">§ ${section3Title}</p>
    <div style="padding-left: 0px;">
        ${section3Content}
    </div>
    <p style="margin-bottom: 0in; line-height: 100%; font-weight:bold">§ ${section4Title}</p>
    <div style="padding-left: 0px;">
        ${section4Content}
    </div>
    <p style="margin-bottom: 0in; line-height: 100%; font-weight:bold">§ ${section5Title}</p>
    <div style="padding-left: 0px;">
        ${section5Content}
    </div>
</div>`;